name: clean_architecture
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  http: ^1.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  


flutter:

  uses-material-design: true

